// design/system/components/core/Avatar.jsx
import React from 'react';

const CSS = `
.wdl-avatar{
  position:relative; display:inline-flex; align-items:center; justify-content:center;
  border-radius:50%; overflow:hidden; flex:none; font-family:var(--font-display);
  font-weight:800; color:#fff; user-select:none;
}
.wdl-avatar img{ width:100%; height:100%; object-fit:cover; display:block; }
.wdl-avatar--xs{ width:28px; height:28px; font-size:11px; }
.wdl-avatar--sm{ width:36px; height:36px; font-size:13px; }
.wdl-avatar--md{ width:48px; height:48px; font-size:17px; }
.wdl-avatar--lg{ width:64px; height:64px; font-size:23px; }
.wdl-avatar--xl{ width:88px; height:88px; font-size:32px; }
.wdl-avatar-wrap{ position:relative; display:inline-flex; }
.wdl-avatar-wrap--ring::after{
  content:""; position:absolute; inset:-4px; border-radius:50%;
  border:3px solid var(--wdl-ring-color, var(--brand)); pointer-events:none;
}
`;

const PALETTE = ['#2f8bff', '#46b1ff', '#14b8b1', '#ff9f45', '#19d894', '#f5365c', '#ffc93d'];
function hashIndex(str = '') {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
  return h % PALETTE.length;
}
function initials(name = '') {
  const parts = name.trim().split(/\s+/);
  return ((parts[0]?.[0] || '') + (parts[1]?.[0] || '')).toUpperCase() || '?';
}

const RING = { gold: 'var(--rank-1)', silver: 'var(--rank-2)', bronze: 'var(--rank-3)', brand: 'var(--brand)', up: 'var(--up)', down: 'var(--down)' };

function useStyleOnce(id, css) {
  if (typeof document !== 'undefined' && !document.getElementById(id)) {
    const el = document.createElement('style');
    el.id = id; el.textContent = css; document.head.appendChild(el);
  }
}

export function Avatar({ src, name = '', size = 'md', ring = null, className = '', ...rest }) {
  useStyleOnce('wdl-avatar-css', CSS);
  const bg = PALETTE[hashIndex(name)];
  const avatar = (
    <span className={`wdl-avatar wdl-avatar--${size} ${className}`} style={{ background: src ? 'transparent' : bg }} {...rest}>
      {src ? <img src={src} alt={name} /> : initials(name)}
    </span>
  );
  if (!ring) return avatar;
  return (
    <span className="wdl-avatar-wrap wdl-avatar-wrap--ring" style={{ '--wdl-ring-color': RING[ring] || ring }}>
      {avatar}
    </span>
  );
}

// app/components/ds/Avatar.vue
<script setup lang="ts">
type Ring = 'gold' | 'silver' | 'bronze' | 'up' | null | undefined

const props = defineProps<{
  name: string
  size?: 'md' | 'lg'
  ring?: Ring
  crown?: boolean   // render a crown centred above the avatar (the current #1)
}>()

// Deterministic color from name
const PALETTE = ['#2f8bff','#19d894','#ff8311','#2dd4cf','#ffc93d','#1f97f0','#f5365c','#14b8b1']
const bg = computed(() => {
  let h = 0
  for (const c of props.name) h = (h << 5) - h + c.charCodeAt(0)
  return PALETTE[Math.abs(h) % PALETTE.length]
})

const initials = computed(() => {
  const parts = props.name.trim().split(/\s+/)
  return parts.length >= 2
    ? ((parts[0]?.[0] ?? '') + (parts[1]?.[0] ?? '')).toUpperCase()
    : props.name.slice(0, 2).toUpperCase()
})

const RING_COLORS: Record<string, string> = {
  gold:   'var(--rank-1)',
  silver: 'var(--rank-2)',
  bronze: 'var(--rank-3)',
  up:     'var(--up)',
}

const boxShadow = computed(() =>
  props.ring ? `0 0 0 3px ${RING_COLORS[props.ring] ?? 'transparent'}` : undefined
)

const crownSize = computed(() => (props.size === 'lg' ? 22 : 16))
</script>

<template>
  <span class="avatar-wrap" :class="`avatar-wrap--${size ?? 'md'}`">
    <span
      class="avatar"
      :class="`avatar--${size ?? 'md'}`"
      :style="{ background: bg, boxShadow }"
      aria-hidden="true"
    >{{ initials }}</span>
    <span v-if="crown" class="avatar__crown" aria-hidden="true">
      <DsCrown :size="crownSize" />
    </span>
  </span>
</template>

<style scoped>
.avatar-wrap { position: relative; display: inline-flex; flex: none; }
.avatar__crown {
  position: absolute;
  top: -0.55em;
  left: 50%;
  transform: translateX(-50%);
  display: inline-flex;
  filter: drop-shadow(0 1px 2px rgba(0,0,0,.5));
  color: var(--rank-1);
}
</style>
